### ISSUE TITLE
Byte data type enhancement

### ISSUE THREAD

**Issue by h20003** [unosquare/tubular#55]
Hello,

Is there any considerations for Byte data type filed in tubular? i have created one project with varbinary field type in sql server but getting worng data in tbgrid  columns. 
e.g, i have following  field order
FirstName,MiddleName,LastName,DOB,PictureByte,IsActive,CreatedDate,ModifiedDate
getting data in following order
Hemal,V,Desai,12-12-1988,true,null,null,null

after picturebyte column all column's data is shifted by 1 column.

Could you please help me on this?

Thanks,
Hemal Desai
Gujarat,India

**Comment by geoperez** [comment]
Hi @hemaldesai, I don't know about your request, the byte array field probably should be handled separated because it could increase the response time. And also if you plan it's to handle images inside the Tubular Grid you may render an img tag to an endpoint, probably with a Row Id, and return the image there.

What do you think @mariodivece ?

**Comment by mariodivece** [comment]
@geoperez agreed. That's why the grid supports full templating. JSON data responses should not contain image data at all. Suggestion: Create an API endpoint that returns the image bytes and link it with a cell template using something like:
`<img ng-src="api/images/{{row.CustomerId}}" alt="{{row.CustomerName}}" />`
